# Algoritmos de optimización - Seminario
Nombre y Apellidos:Fabian Enrique Hooker Cruz
Url:
Problema:Organizar sesiones de doblaje(I)

Sesiones de doblaje
Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible. Los datos son:
Número de actores: 10
Número de tomas : 30
Actores/Tomas : https://bit.ly/36D8IuK
- 1 indica que el actor participa en la toma
- 0 en caso contrario
(*) La respuesta es obligatoria

1)Preguntas
Datos donde: 
A=Actores
T= Tomas
D=Dias
R=Retriciones
TTD= Tomas Total al dias

(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?


R=teniendo en cuenta solo de pede de la catidad de tomas entre el numero de dias disponible

TTD=T/D 

¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones?

R=Para calcular el número de posibilidades teniendo en cuenta todas las restricciones, como la limitación de no grabar
más de 6 tomas por día y la necesidad de que los actores coincidan en las tomas en las que sus personajes aparecen 
juntos, es necesario utilizar un enfoque como el algoritmo voraz o la búsqueda heurística que se mencionó anteriormente. 
Estos enfoques consideran las restricciones y exploran diferentes combinaciones de tomas en los días de grabación para 
encontrar la mejor planificación que minimice la cantidad de días de grabación y, por lo tanto, el costo total de los 
servicios de los actores de doblaje. Sin embargo, debido a la complejidad del problema, no podemos calcular el número 
exacto de posibilidades con restricciones sin hacer una búsqueda exhaustiva usado algoritmo voraz o la búsqueda heurística.


2)Preguntas

(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)
R=Descargue el archivo en formato excel usado la liberia de panda importe,
El DataFrame de Pandas es una estructura de datos bidimensional que puede contener datos heterogéneos con etiquetas en filas y columnas. Es una herramienta poderosa para la manipulación y análisis de datos tabulares, lo que lo convierte en una excelente opción para este problema.
Razones para elegir DataFrame de Pandas:
Flexibilidad en la manipulación de datos: Pandas proporciona una gran variedad de métodos y funciones para realizar operaciones como filtrado, agrupación, transformación, unión, etc., en los datos. Esto permite una manipulación más sencilla y eficiente de los datos para cumplir con las restricciones y objetivos del problema.
Integración con otras bibliotecas: Pandas se integra bien con otras bibliotecas populares de Python utilizadas en ciencia de datos, como NumPy, Matplotlib y SciPy. Esto facilita la realización de análisis y visualización de datos si fuera necesario.
Facilidad de lectura y escritura de datos: Pandas es capaz de leer y escribir datos en diversos formatos, como CSV, Excel, SQL, entre otros. Esto hace que sea sencillo importar y exportar los datos, lo cual es útil si necesitamos trabajar con datos provenientes de diferentes fuentes.
Manipulación de datos faltantes: Pandas maneja de manera eficiente los datos faltantes (NaN) y ofrece diversas herramientas para tratarlos, como eliminar filas o columnas con valores faltantes o rellenarlos con valores adecuados según el contexto.
Eficiencia computacional: Pandas está optimizado para ofrecer un buen rendimiento en operaciones sobre grandes conjuntos de datos. Esto es importante, ya que el problema puede implicar una gran cantidad de tomas y actores, lo que requeriría un manejo eficiente de los datos.






3)Preguntas

(*)¿Cual es la función objetivo?
La función objetivo en este problema es minimizar el costo total de los servicios de los actores de doblaje. El objetivo es 
planificar las sesiones por día de manera que se graben todas las tomas necesarias, pero utilizando la menor cantidad de días 
de grabación posible, lo que reduce los costos de desplazamiento de los actores. Como los actores cobran toda la misma cantidad 
por cada día que deben desplazarse, al minimizar la cantidad de días de grabación,se minimiza el costo total de los servicios
de los actores.

(*)¿Es un problema de maximización o minimización?
Es un problema de minimización. El objetivo es minimizar el costo total de los servicios de los actores de doblaje 
al planificar las sesiones por día de manera eficiente y reducir la cantidad de días de grabación necesarios. 
El objetivo es encontrar la solución que resulte en el menor gasto posible, lo que implica minimizar la función objetivo.

In [ ]:
#Usaremos la siguietne libreria
import numpy as np
import pandas as pd
import os.path
import matplotlib.pyplot as plt



In [260]:
columnas_a_omitir = ['Total']

#dfActoresTomas = pd.read_excel('dataset/Datos problema doblaje(30 tomas, 10 actores).xlsx',sheet_name='Hoja 1',header=0, skiprows=1, usecols=lambda col: col not in columnas_a_omitir, skipfooter=1) 
dfActoresTomas = pd.read_excel('dataset/Datos problema doblaje(30 tomas, 10 actores).xlsx',sheet_name='Hoja 1',header=0, skiprows=1, usecols=lambda col: col not in columnas_a_omitir,skipfooter=1, index_col=None) 
dfActoresTomas = dfActoresTomas.dropna(axis=1, how='all').dropna()

display(dfActoresTomas)


Toma    1    2    3    4    5    6    7    8    9   10
0    1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
1    2.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
2    3.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
3    4.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
4    5.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
5    6.0  1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
6    7.0  1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
7    8.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
8    9.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
9   10.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0
10  11.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
11  12.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0
12  13.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
13  14.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
14  15.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
15  16.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0
16  17.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
17  18.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
18  19.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
19  20.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
20  21.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
21  22.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
22  23.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
23  24.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
24  25.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0
25  26.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
26  27.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
27  28.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
28  29.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0
29  30.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0

In [261]:
df = pd.DataFrame(dfActoresTomas)
#display(df)

tomas = df['Toma'].astype(int).values.reshape(-1, 1)
tomas_actores = df.astype(int).drop(columns=['Toma']).values

print(type(tomas_actores))
print(type(tomas))

display(tomas)
display(tomas_actores)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30]])

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 1, 0,

In [258]:

def Usofuerza_bruta(tomas, tomas_actores):
    
    dia = 1
    solucion = np.zeros((len(tomas),3)).astype(int)
    matriz_tomas = np.zeros(10, dtype=int).reshape(1,10)


    for idx, toma in enumerate(tomas):
        # Obtiene la toma actual de la matriz de tomas
        toma_actual = tomas_actores[toma-1]
        
        # Calcula la diferencia de matrices entre la matriz actual y la matriz de tomas
        diferencia = np.subtract(toma_actual, np.add.reduce(matriz_tomas, axis=0))
        diferencia[diferencia < 0] = 0

        # Agrega la toma actual a la matriz de tomas
        matriz_tomas = np.append(matriz_tomas, toma_actual, axis=0)
        
        #Almacenamos el día, número de toma y costo adicional de la toma
        solucion[idx] = [dia, toma[0], diferencia.sum()]


        # Verifica el número de días máximo para las tomas
        if(toma%6==0):
            # Inicia desde cero la matriz de toma
            matriz_tomas = np.zeros(10, dtype=int).reshape(1,10)
            dia+=1
    return solucion



solucion_optima = Usofuerza_bruta(tomas,tomas_actores)
total_dias_grabacion = solucion_optima[:, -1].max()
print(solucion_optima) 
print("Cantidad de dia optimo")
print("Total de días de grabación:", total_dias_grabacion)

[[ 1  1  5]
 [ 1  2  0]
 [ 1  3  1]
 [ 1  4  1]
 [ 1  5  0]
 [ 1  6  0]
 [ 2  7  4]
 [ 2  8  1]
 [ 2  9  0]
 [ 2 10  1]
 [ 2 11  2]
 [ 2 12  0]
 [ 3 13  3]
 [ 3 14  2]
 [ 3 15  2]
 [ 3 16  1]
 [ 3 17  0]
 [ 3 18  0]
 [ 4 19  2]
 [ 4 20  2]
 [ 4 21  2]
 [ 4 22  1]
 [ 4 23  0]
 [ 4 24  0]
 [ 5 25  4]
 [ 5 26  3]
 [ 5 27  0]
 [ 5 28  0]
 [ 5 29  1]
 [ 5 30  0]]
Cantidad de dia optimo
Total de días de grabación: 5


4)Calcula la complejidad del algoritmo por fuerza bruta

Para calcular la complejidad del algoritmo por fuerza bruta, vamos a analizar el costo de las operaciones realizadas en el bucle principal:

El bucle for itera sobre cada toma en la variable tomas. La longitud de tomas es n (30 en este caso).

En cada iteración del bucle, se realiza lo siguiente:
a. Se obtiene la toma_actual de tomas_actores, que tiene una complejidad O(1).
b. Se calcula la diferencia de matrices diferencia entre la toma_actual y la suma reducida de matriz_tomas. La suma reducida tiene una complejidad O(10) (ya que la matriz tiene 10 columnas).
c. Se realiza una operación de comparación y asignación de los elementos de diferencia que son menores que 0, lo cual tiene una complejidad O(10).
d. Se agrega la toma_actual a matriz_tomas, que tiene una complejidad O(10).
e. Se almacena el día, número de toma y costo adicional en la matriz solucion, que tiene una complejidad O(1).

Además, en cada iteración, se verifica si el número de toma es divisible por 6 para reiniciar matriz_tomas y aumentar dia. Esta operación tiene una complejidad O(10).

Por lo tanto, el costo total del bucle for sería aproximadamente:

Costo del bucle for = n * (O(1) + O(10) + O(10) + O(10) + O(10) + O(1)) = n * O(10) = O(n)

La complejidad del algoritmo por fuerza bruta es O(n), donde n es el número de tomas. En este caso, como n=30, la complejidad es lineal con respecto a la cantidad de tomas y, por lo tanto, el algoritmo es bastante eficiente para este tamaño de entrada.


5)(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

In [264]:

def planificar_doblaje(tomas, tomas_actores):
    n = len(tomas)
    capacidad_maxima = 6

    # Inicializar matriz dp con ceros
    dp = np.zeros((n + 1, capacidad_maxima + 1), dtype=int)

    # Recorrer cada toma y capacidad actual
    for i in range(1, n + 1):
        for capacidad_actual in range(1, capacidad_maxima + 1):
            peso_toma_i = tomas_actores[tomas[i - 1] - 1]
            if peso_toma_i.sum() <= capacidad_actual:
                dp[i][capacidad_actual] = max(
                    tomas[i - 1], dp[i - 1][capacidad_actual - peso_toma_i.sum()]
                )
            else:
                dp[i][capacidad_actual] = dp[i - 1][capacidad_actual]

    # Reconstruir la solución óptima
    solucion = []
    dia = 1
    capacidad_actual = capacidad_maxima
    for i in range(n, 0, -1):
        if dp[i][capacidad_actual] != dp[i - 1][capacidad_actual]:
            # Almacenar los valores de la toma en una lista temporal
            toma_actual = [dia, tomas[i - 1], tomas_actores[tomas[i - 1] - 1].sum()]
            solucion.append(toma_actual)
            capacidad_actual -= tomas_actores[tomas[i - 1] - 1].sum()
        if tomas[i - 1] % 6 == 0:
            dia += 1

    # Convertir la lista de solución en un numpy array
    solucion = np.array(solucion)

    return solucion

# Crear el array a una dimencion
tomas = tomas.reshape(-1)
display(tomas)




solucion_optima = planificar_doblaje(tomas, tomas_actores)
total_dias_grabacion = solucion_optima[:, -1].max()

print(solucion_optima)
print("Total de días de grabación:", total_dias_grabacion)






array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

[[ 1 30  2]
 [ 2 29  3]]
Total de días de grabación: 3


6)(*)Calcula la complejidad del algoritmo

R=La complejidad del algoritmo se puede analizar por partes:
Creación de la matriz dp:
Tiene dimensiones (n + 1) x (capacidad_maxima + 1).
Se realiza una doble iteración con dos bucles for anidados que recorren n y capacidad_maxima.
La complejidad de esta parte es O(n * capacidad_maxima).
Reconstrucción de la solución óptima:
Se realiza una iteración desde n hasta 1 en orden inverso.
Dentro de este bucle, hay algunas operaciones adicionales, pero como estamos iterando sobre n elementos, la complejidad sigue siendo O(n).
En general, el algoritmo se puede simplificar a O(n * capacidad_maxima) en su complejidad de tiempo. En este caso particular, dado que la capacidad máxima es 6, podemos considerar que la complejidad del algoritmo es O(n) en la práctica. Esto significa que el algoritmo es lineal y tiene un buen rendimiento para instancias razonablemente grandes.
Cabe mencionar que la complejidad del algoritmo depende de la capacidad máxima y el tamaño de la entrada n. Si la capacidad máxima fuera muy grande, la complejidad aumentaría en consecuencia. Sin embargo, en el contexto de este problema específico, la capacidad máxima está fijada en 6, lo que nos permite tratarlo como una complejidad lineal en la práctica.


7)Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

In [266]:
def generar_juego_datos(num_actores, num_tomas):
    # Generar las tomas aleatoriamente
    tomas = np.arange(1, num_tomas + 1)

    # Generar las matrices de tomas para los actores de manera aleatoria
    tomas_actores = np.random.randint(2, size=(num_tomas, num_actores))

    return tomas, tomas_actores

# Ejemplo de uso con 10 actores y 30 tomas
num_actores = 10
num_tomas = 30
tomas, tomas_actores = generar_juego_datos(num_actores, num_tomas)

print("Tomas:")
print(tomas)

print("\nTomas de actores:")
print(tomas_actores)

Tomas:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]

Tomas de actores:
[[0 1 1 1 0 0 1 1 0 0]
 [1 0 0 1 1 1 1 0 1 1]
 [0 1 0 0 1 1 0 0 0 1]
 [1 1 0 0 1 1 0 0 0 0]
 [0 0 1 1 0 1 0 1 1 1]
 [0 1 1 0 1 0 0 1 1 1]
 [1 1 1 0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1 0 1 1]
 [0 0 1 0 1 1 0 0 1 1]
 [1 0 1 1 0 1 1 0 0 0]
 [1 1 0 1 1 0 1 0 1 0]
 [1 0 0 0 0 0 0 1 0 1]
 [1 1 1 1 1 1 1 0 1 1]
 [1 1 0 0 0 1 1 1 0 1]
 [0 0 0 0 1 0 1 1 0 1]
 [1 1 1 0 0 1 1 1 1 1]
 [1 1 1 1 0 0 0 1 0 0]
 [0 1 1 1 1 0 1 1 1 1]
 [0 1 0 1 1 1 1 0 1 0]
 [0 0 1 1 0 0 1 1 1 0]
 [1 0 0 0 1 0 1 1 0 1]
 [1 1 1 0 1 0 1 0 1 1]
 [1 1 0 0 0 1 1 0 0 1]
 [1 1 1 0 0 0 1 0 1 1]
 [1 0 1 0 1 0 1 0 1 0]
 [1 1 1 0 1 1 0 0 1 0]
 [1 0 1 0 1 0 1 0 1 1]
 [0 0 1 1 0 1 1 1 1 1]
 [0 0 0 1 0 1 1 0 1 0]
 [1 1 1 1 0 0 1 0 1 0]]


8)Aplica el algoritmo al juego de datos generado

In [267]:
def planificar_doblaje(tomas, tomas_actores):
    n = len(tomas)
    capacidad_maxima = 6

    # Inicializar matriz dp con ceros
    dp = np.zeros((n + 1, capacidad_maxima + 1), dtype=int)

    # Recorrer cada toma y capacidad actual
    for i in range(1, n + 1):
        for capacidad_actual in range(1, capacidad_maxima + 1):
            peso_toma_i = tomas_actores[tomas[i - 1] - 1]
            if peso_toma_i.sum() <= capacidad_actual:
                dp[i][capacidad_actual] = max(
                    tomas[i - 1], dp[i - 1][capacidad_actual - peso_toma_i.sum()]
                )
            else:
                dp[i][capacidad_actual] = dp[i - 1][capacidad_actual]

    # Reconstruir la solución óptima
    solucion = []
    dia = 1
    capacidad_actual = capacidad_maxima
    for i in range(n, 0, -1):
        if dp[i][capacidad_actual] != dp[i - 1][capacidad_actual]:
            # Almacenar los valores de la toma en una lista temporal
            toma_actual = [dia, tomas[i - 1], tomas_actores[tomas[i - 1] - 1].sum()]
            solucion.append(toma_actual)
            capacidad_actual -= tomas_actores[tomas[i - 1] - 1].sum()
        if tomas[i - 1] % 6 == 0:
            dia += 1

    # Convertir la lista de solución en un numpy array
    solucion = np.array(solucion)

    return solucion

# Crear el array a una dimencion
tomas = tomas.reshape(-1)
display(tomas)




solucion_optima = planificar_doblaje(tomas, tomas_actores)
total_dias_grabacion = solucion_optima[:, -1].max()

print(solucion_optima)
print("Total de días de grabación:", total_dias_grabacion)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

[[ 1 30  6]]
Total de días de grabación: 6


9)Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo

10)Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño


Para avanzar en el estudio del problema de planificación de doblaje, se pueden seguir varias líneas de investigación y enfoques:
Optimización de algoritmos existentes: Se puede buscar mejorar la complejidad de los algoritmos existentes para encontrar una solución más rápida y eficiente para el problema. Además, se pueden explorar técnicas de optimización como programación dinámica, algoritmos de ramificación y poda, y algoritmos genéticos para encontrar soluciones óptimas o cercanas a la óptima.
Heurísticas y metaheurísticas: Se pueden aplicar heurísticas y metaheurísticas para obtener soluciones aproximadas en tiempos más cortos. Algoritmos como la búsqueda local, recocido simulado, colonia de hormigas, entre otros, pueden ser utilizados para encontrar soluciones de buena calidad en problemas grandes.
Modelado más realista: Se puede estudiar cómo incorporar más restricciones y consideraciones del mundo real en el problema de planificación de doblaje, como la disponibilidad de actores en días específicos, costos variables para los actores según su demanda, etc.
Análisis de casos específicos: Dependiendo del contexto de la industria del doblaje y los requisitos de la producción de películas, se pueden analizar casos específicos con restricciones adicionales y características particulares para diseñar soluciones personalizadas.
Big Data y Machine Learning: Con la creciente cantidad de datos en la industria del entretenimiento, se pueden aplicar técnicas de Big Data y Machine Learning para optimizar la asignación de actores a tomas y encontrar patrones que ayuden en la toma de decisiones.
Variaciones del problema: Además de la asignación de actores, se pueden explorar otras variaciones del problema de planificación en la industria del entretenimiento, como la asignación de horarios para grabación, asignación de recursos técnicos, entre otros.
En cuanto a las variaciones al alza del tamaño, es importante considerar que, a medida que el número de actores y tomas aumenta, el problema puede volverse exponencialmente más difícil de resolver. Por lo tanto, será esencial buscar enfoques más eficientes y escalables para hacer frente a conjuntos de datos más grandes.
